team-gryff/react-monocle

package.json
Production libs: react, react-dom, d3
Development libs: babel, chai, mocha, enzyme, jsdom, webpack
=> Initialize npm packages

.travis.yml, test/astParserTest.js, test/test.js
Update travis config to test for Node v4.0 versions
=> Add test folder and update travis config

package.json, src/reactParser.js, src/test/reactParserTest.js, src/test/test.js, test/astParserTest.js
- add acorn, escodegen, esrecurse libraries for parsing
- add reactParser script and unit test for it
=> Parsing branch

.gitignore, src/reactParser.js, src/test/reactParserTest.js
- add .DS_Store to .gitignore
- partially finish getES5ReactComponents and getES6ReactComponents, returning object with name of top-level components
- does not take into account nested component hierarchies yet
=> update gitignore and finish implementing parser helper functions

src/reactParser.js, src/test/reactParserTest.js
- filter out non-custom jsx components when parsing nested child jsx components
=> refactor es5 react component parser function

src/test/fixtures/es5ReactComponentFixtures.js, src/test/fixtures/es6ReactComponentFixtures.js, src/test/reactParserTest.js
- created seperate es5 and es6 fixture js files
=> moved testing fixtures to seperate file

src/reactParser.js, src/test/fixtures/es5ReactComponentFixtures.js, src/test/reactParserTest.js
- add fixture for component with props
- add unit test for testing parse output with component with props
- update es5 parser to include props property
=> update es5 react component parser to include props property

src/reactParser.js, src/test/fixtures/es6ReactComponentFixtures.js, src/test/reactParserTest.js
- add jsdocs documentation for react parser functions
- add unit test fixtures to test es6 React component prop parsing
- fix unit test missing props property
- merge changes for CLI, add unit tests for astGenerator and d3DataBuilder
=> add jsdocs, add test fixtures, fix unit test, merge changes

spec/d3Tree-spec.js, src/d3Tree/d3Tree.html, src/d3Tree/d3Tree.js, src/test/d3TreeTest.js, src/test/test.js
- split d3 tree code into functions
- implemented additional features to tree
- switching testing environment to mocha/chai
=> refactored d3 tree 

.gitignore, src/test/test.js
- add bundle.map.js to .gitignore
- remove d3tree unit testing suite until further investigation can be done using headless browsers
=> update gitignore, comment d3tree component testing

package.json, src/test/d3DataBuilderTest.js
- remove verbose npm error debug logging
- disable d3DataBuilder unit tests until ready
=> update package.json and disable unit test

package.json, src/reactParser.js, src/test/fixtures/es5ReactComponentFixtures.js, src/test/reactParserTest.js
- is there a better way to besides using eval?
=> finish es5 react state parsing

src/constants.js, src/d3Tree/d3Tree.html, src/reactParser.js, src/test/fixtures/dummyTree.js, src/test/fixtures/es5ReactComponentFixtures.js, src/test/fixtures/es6ReactComponentFixtures.js, src/test/reactParserTest.js
- merge @jerrymao15 #33 fix
- add new constants.js file
- modularize unit tests, break out fixture-specific code from unit tests to fixture files
=> merge es6 state parsing fix, conflicts, refactor unit tests

src/constants.js, src/reactParser.js, src/test/fixtures/dummyTree.js, src/test/fixtures/es5ReactComponentFixtures.js, src/test/fixtures/es6ReactComponentFixtures.js, src/test/reactParserTest.js
- add unit tests and fixtures for es5 and es6 method parsing
- implement es6 method parsing
=> implement es6 method parsing

src/reactParser.js, src/test/fixtures/es5ReactComponentFixtures.js, src/test/fixtures/es6ReactComponentFixtures.js, src/test/fixtures/reactParserOutputFixtures.js, src/test/reactParserTest.js
- Merge @jerrymao15 pull request #39 
- rearrange function definitions in reactParser.js
- extract common es5 and es6 output fixtures to single output fixtures js file
=> Merge #39, rearrange functions, modularize fixtures

src/reactParser.js, src/test/fixtures/commonReactComponentFixtures.js, src/test/fixtures/reactParserOutputFixtures.js, src/test/reactParserTest.js
- add unit tests and fixtures for es5 and es6 parsing of components using composition
- remove duplicate function definitions in reactParser file
=> add component composition unit tests, remove duplication function definitions

.eslintignore, .eslintrc, .travis.yml, package.json, src/astGenerator.js, src/constants.js, src/d3DataBuilder.js, src/reactParser.js
- add eslint module
- add npm lint script
- fix first pass linting of src folder
=> setup eslint, fix linter issues

src/reactParser.js, src/test/fixtures/dummyTree.js, src/test/fixtures/reactParserOutputFixtures.js
- updated props array to include value and parent properties
- updated relevant tests to account for new properties in props array
=> Added 'value' and 'parent' properties to objects of props array

src/previewParser.js, src/test/fixtures/bundleFileFixture.js, src/test/previewParserTest.js
- search user's bundle file for mount location and replace with uniform div id
- corresponding tests written
=> parse user's bundle.js file

bin/cmd.js, src/d3Tree/d3Tree.html, src/d3Tree/renderHtml.js, src/previewParser.js, src/test/fixtures/bundleFileFixture.js, src/test/previewParserTest.js
- parse user's bundled react code to wrap all setState functions in 'wrapper' function
- inject updated bundle file into renderHtml file
=> render user's app beside monocle tree

bin/cmd.js, react/actions/index.js, react/index.jsx, react/reducers/monocleApp.js, src/d3Tree/renderHtml.js, src/previewParser.js, src/reactInterceptor.js, src/test/reactInterceptorTest.js
- hijack 'getInitialState' and 'this.state' functions to send initial state to redux store to obtain live data on initial render of monocle app
- get all 'div' id's from user's bundle file to inject in monocle html file to mount user's app beside tree
=> send initial state to redux store

react/components/Graph.jsx, react/components/Node.jsx
=> another refactor on prop link highlighting

README.md, bin/cmd.js, package.json, src/htmlParser.js
added support for  double slash in html
updated readme
=> made HTML optional
